// For delete, make checkbox, spinner, label, whatever invisible
// For add, add to database AND change invisiblelabel to the new name, add the spinner


package pkgPizza;

import java.awt.Component;
import java.sql.*;
import java.util.*;
import java.awt.Color;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddDeleteUI1 extends javax.swing.JFrame {

    private static Connection conn = DBSingle.getConn().getConnection();
    private Component frame;
    
    public AddDeleteUI1() {
        initComponents();
        getContentPane().setBackground(Color.getHSBColor(249,238,205));
        fillcboIngredients();
    }
    
    
    
    
    public void fillcboIngredients()
    {

        String strIngredientsList;

        try
        {
           Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
           stmt.executeQuery("SELECT * FROM ingredients where Active = true");
           ResultSet rs1 = stmt.getResultSet();

           cboIngredients.removeAllItems();

           while(rs1.next())
           {
                Ingredients myIngredients = new Ingredients();
                myIngredients.setId(Integer.parseInt(rs1.getString("Ingredients_ID")));
                myIngredients.setDescription(rs1.getString("Description"));
                cboIngredients.addItem(myIngredients);
                myIngredients = null;

           }
           
        }
        catch(SQLException ex)
        {

        }
    }
    
    
    public void close()
    {
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtXLarge = new javax.swing.JTextField();
        txtLarge = new javax.swing.JTextField();
        txtPersonal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSmall = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnClearAddItem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNewItem = new javax.swing.JTextField();
        txtMedium = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReOrder = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboIngredients = new javax.swing.JComboBox();
        btnDeleteItem = new javax.swing.JButton();
        btnClearDeleteItem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPizzajpg = new javax.swing.JLabel();
        pnlGreenStripe = new javax.swing.JPanel();
        pnlBlueStripe = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMainMenu = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(249, 238, 205));

        txtXLarge.setFont(new java.awt.Font("Garamond", 0, 18));

        txtLarge.setFont(new java.awt.Font("Garamond", 0, 18));

        txtPersonal.setFont(new java.awt.Font("Garamond", 0, 18));

        jLabel11.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel11.setText("Personal:");

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 18));
        jLabel10.setText("Enter Amount of Item on Pizza:");

        jLabel9.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel9.setText("oz.");

        txtSmall.setFont(new java.awt.Font("Garamond", 0, 18));

        btnAddItem.setFont(new java.awt.Font("Garamond", 0, 18));
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnClearAddItem.setFont(new java.awt.Font("Garamond", 0, 18));
        btnClearAddItem.setText("Clear");
        btnClearAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAddItemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel5.setText("Extra Large:");

        jLabel4.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel4.setText("Large:");

        jLabel3.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        jLabel3.setText("Medium:");

        jLabel2.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel2.setText("Small:");

        txtNewItem.setFont(new java.awt.Font("Garamond", 0, 18));

        txtMedium.setFont(new java.awt.Font("Garamond", 0, 18));

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel1.setText("New Item:");

        jLabel6.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel6.setText("Add Item");

        txtReOrder.setFont(new java.awt.Font("Garamond", 0, 18));

        jLabel8.setFont(new java.awt.Font("Garamond", 0, 18));
        jLabel8.setText("Enter Re-Order Amount for Item:");

        cboIngredients.setFont(new java.awt.Font("Garamond", 0, 18));
        cboIngredients.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIngredientsActionPerformed(evt);
            }
        });

        btnDeleteItem.setFont(new java.awt.Font("Garamond", 0, 18));
        btnDeleteItem.setText("Delete Item");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnClearDeleteItem.setFont(new java.awt.Font("Garamond", 0, 18));
        btnClearDeleteItem.setText("Clear");
        btnClearDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDeleteItemActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setText("Delete Item");

        jPanel1.setBackground(new java.awt.Color(0, 0, 141));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        lblPizzajpg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgPizza/tomato_pizza.jpg"))); // NOI18N
        lblPizzajpg.setText("lblPizzaPic");
        lblPizzajpg.setAlignmentY(0.0F);
        lblPizzajpg.setFocusable(false);
        lblPizzajpg.setIconTextGap(0);
        lblPizzajpg.setInheritsPopupMenu(false);

        pnlGreenStripe.setBackground(new java.awt.Color(0, 153, 0));
        pnlGreenStripe.setAlignmentY(0.4F);
        pnlGreenStripe.setPreferredSize(new java.awt.Dimension(420, 30));
        pnlGreenStripe.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlGreenStripeLayout = new javax.swing.GroupLayout(pnlGreenStripe);
        pnlGreenStripe.setLayout(pnlGreenStripeLayout);
        pnlGreenStripeLayout.setHorizontalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
        );
        pnlGreenStripeLayout.setVerticalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        pnlBlueStripe.setBackground(new java.awt.Color(0, 0, 141));
        pnlBlueStripe.setAlignmentX(0.0F);
        pnlBlueStripe.setAlignmentY(0.0F);
        pnlBlueStripe.setFocusable(false);
        pnlBlueStripe.setPreferredSize(new java.awt.Dimension(590, 30));

        javax.swing.GroupLayout pnlBlueStripeLayout = new javax.swing.GroupLayout(pnlBlueStripe);
        pnlBlueStripe.setLayout(pnlBlueStripeLayout);
        pnlBlueStripeLayout.setHorizontalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
        );
        pnlBlueStripeLayout.setVerticalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel12.setText("CJS Pizza");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBlueStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                    .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(666, 666, 666)
                .addComponent(txtNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel10)
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel8)
                            .addGap(58, 58, 58))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(318, 318, 318)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClearAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtXLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtReOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddItem)))
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(btnClearDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addComponent(btnDeleteItem)
                .addGap(472, 472, 472))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jLabel12))
                .addGap(628, 628, 628))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(cboIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(582, 582, 582))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(634, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(632, 632, 632))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSmall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtLarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtXLarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnClearAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cboIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteItem)
                    .addComponent(btnClearDeleteItem))
                .addGap(60, 60, 60))
        );

        mnuFile.setText("File");

        mnuMainMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnuMainMenu.setText("Main Menu");
        mnuMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainMenuActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMainMenu);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnClearAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAddItemActionPerformed
    txtNewItem.setText(null);
    txtPersonal.setText(null);
    txtSmall.setText(null);
    txtMedium.setText(null);
    txtLarge.setText(null);
    txtXLarge.setText(null);
    txtReOrder.setText(null);
}//GEN-LAST:event_btnClearAddItemActionPerformed

private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed

       String strNewItem;
       int intPersonal;
       int intSmall;
       int intMedium;
       int intLarge;
       int intXLarge;


        strNewItem = txtNewItem.getText();
        System.out.println(strNewItem);
        intPersonal = Integer.parseInt(String.valueOf(txtPersonal.getText()));
        intSmall = Integer.parseInt(String.valueOf(txtSmall.getText()));
        intMedium = Integer.parseInt(String.valueOf(txtMedium.getText()));
        intLarge = Integer.parseInt(String.valueOf(txtLarge.getText()));
        intXLarge = Integer.parseInt(String.valueOf(txtXLarge.getText()));

         
        
        
        try
        {
            
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            String update = "SELECT Ingredients_ID FROM ingredients WHERE Active = false AND Description like (\"inact%\") order by Ingredients_ID limit 1;";

            System.out.println(update);


            
            ResultSet rs = stmt.executeQuery(update);
            if (rs.first() == true){
            System.out.println(rs.getInt("Ingredients_ID"));
            String update2 = "UPDATE ingredients set Description = '" + strNewItem + "', ReOrder = '" + txtReOrder.getText() + "', Active = true where Ingredients_ID = " + rs.getInt("Ingredients_ID");
            String update4 = "UPDATE ingredients_usage set UsageAmount = " + intPersonal + " where Ingredients_ID = " + rs.getInt("Ingredients_ID") + " AND Size_ID = " + 400001 + ";";
            String update5 = "UPDATE ingredients_usage set UsageAmount = " + intSmall + " where Ingredients_ID = " + rs.getInt("Ingredients_ID") + " AND Size_ID = " + 400002 + ";";
            String update6 = "UPDATE ingredients_usage set UsageAmount = " + intMedium + " where Ingredients_ID = " + rs.getInt("Ingredients_ID") + " AND Size_ID = " + 400003 + ";";
            String update7 = "UPDATE ingredients_usage set UsageAmount = " + intLarge + " where Ingredients_ID = " + rs.getInt("Ingredients_ID") + " AND Size_ID = " + 400004 + ";";
            String update8 = "UPDATE ingredients_usage set UsageAmount = " + intXLarge + " where Ingredients_ID = " + rs.getInt("Ingredients_ID") + " AND Size_ID = " + 400005 + ";";
            
                
            stmt.executeUpdate(update2);
            stmt.executeUpdate(update4);
            stmt.executeUpdate(update5);
            stmt.executeUpdate(update6);
            stmt.executeUpdate(update7);
            stmt.executeUpdate(update8);
            
            
            
            JOptionPane.showMessageDialog(frame,
            "Item added.");
            }
            else
            {
                JOptionPane.showMessageDialog(frame,"You've used up all of your empty inventory spots. Please contact CJS Software Solutions to add further ingredients.","All Available Inventory Spots Are Used",
                JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(Exception e)

                {
                    System.out.println(e.getMessage());
                }
        
        
    txtNewItem.setText(null);
    txtPersonal.setText(null);
    txtSmall.setText(null);
    txtMedium.setText(null);
    txtLarge.setText(null);
    txtXLarge.setText(null);
    txtReOrder.setText(null);
        
    
    
    
    
}//GEN-LAST:event_btnAddItemActionPerformed

private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
    int result = JOptionPane.showConfirmDialog(
    frame,
    "Are you sure you want to exit?",
    "CJS Software Solutions",
    JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        System.exit(0);
    }           

    
}//GEN-LAST:event_mnuExitActionPerformed

private void mnuMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainMenuActionPerformed
        this.dispose();
        MainMenuUI mainMenu = new MainMenuUI();
        mainMenu.setVisible(true);
        mainMenu.enableButtons();
}//GEN-LAST:event_mnuMainMenuActionPerformed

private void cboIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIngredientsActionPerformed
    if (cboIngredients.getSelectedIndex() >= 0)
    {
    try
        {
            btnDeleteItem.setEnabled(true);
               Ingredients myIngredients = new Ingredients();
               myIngredients = (Ingredients) cboIngredients.getSelectedItem();
        }
        catch(Exception ex)
        {

        }
    }
    else
    {
        btnDeleteItem.setEnabled(false);
    }
}//GEN-LAST:event_cboIngredientsActionPerformed

private void btnClearDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDeleteItemActionPerformed
    cboIngredients.setSelectedIndex(0);
}//GEN-LAST:event_btnClearDeleteItemActionPerformed

private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
    // In the active column, it makes it false.
    // Change ReOrder to 0.

    
    Ingredients myIngredients = (Ingredients)cboIngredients.getSelectedItem();
    
 int result = JOptionPane.showConfirmDialog(
    frame,
    "Are you sure you want to delete this item?",
    "CJS Software Solutions",
    JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
               
       try
        {
            
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            
            String update9 = "UPDATE ingredients set Active = false, ReOrder = 0 where Ingredients_ID = " + myIngredients.getId() + ";";
           
            System.out.println(update9);
            stmt.executeUpdate(update9);
            
            JOptionPane.showMessageDialog(frame,
            "Item deleted.");
            
            stmt.executeQuery("SELECT * FROM ingredients where Active = true");
            
        }
        catch(Exception e)

                {
                    System.out.println(e.getMessage());
                }
    }
    cboIngredients.setSelectedIndex(0);
        
        

        
        
       
    
}//GEN-LAST:event_btnDeleteItemActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDeleteUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddDeleteUI1().setVisible(true);
            }
        });
    }
    
    
    // personal variables
    String ingredients;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClearAddItem;
    private javax.swing.JButton btnClearDeleteItem;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JComboBox cboIngredients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPizzajpg;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuMainMenu;
    private javax.swing.JPanel pnlBlueStripe;
    private javax.swing.JPanel pnlGreenStripe;
    private javax.swing.JTextField txtLarge;
    private javax.swing.JTextField txtMedium;
    private javax.swing.JTextField txtNewItem;
    private javax.swing.JTextField txtPersonal;
    private javax.swing.JTextField txtReOrder;
    private javax.swing.JTextField txtSmall;
    private javax.swing.JTextField txtXLarge;
    // End of variables declaration//GEN-END:variables
}
