/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InitialOrderUI.java
 *
 * Created on Oct 1, 2011, 10:19:57 PM
 */

package pkgPizza;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JRadioButton;


/**
 *
 * @author Steve
 */
public class OrderInfoUI extends javax.swing.JFrame {

    private static Connection conn = DBSingle.getConn().getConnection();

    /** Creates new form InitialOrderUI */
    public OrderInfoUI()
    {
        initComponents();
    }

    public void insertNewOrder()
    {
        //get customer_ID so that it can be inserted along with other info
//        try
//        {
//            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
//            stmt.executeQuery("SELECT * FROM customers WHERE CustomerLast = '" + customerLast + "' AND Phone = '" + customerPhone + "';");
//            ResultSet rs1 = stmt.getResultSet();
//
//            while(rs1.next())
//            {
//               // cusID = rs1.getInt("Customer_ID");
//               cusID = rs1.getInt(1);
//               System.out.println("" + cusID);
//            }
//            System.out.println(cusID);
//        }
//        catch(SQLException ex)
//        {
//            System.out.println(ex.getMessage());
//        }

        try
        {
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stmt.executeUpdate("INSERT INTO customer_orders (Customer_ID, OrderType, OrderDate) VALUES ('" + cusID + "','" + OrderType + "', NOW());");

            stmt.executeQuery("SELECT MAX(CustomerOrder_ID) FROM customer_orders");
            ResultSet rs1 = stmt.getResultSet();

            while(rs1.next())
            {
                orderNum = rs1.getInt("MAX(CustomerOrder_ID)");
            }
        }

        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
        public void findCustomer()
    {
        customerPhone = txtCustomerPhone.getText();
        customerLast = txtCustomerLastName.getText();

        try
        {
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stmt.executeQuery("SELECT * FROM customers WHERE CustomerLast = '" + customerLast + "' AND Phone = '" + customerPhone + "'");
            ResultSet rs1 = stmt.getResultSet();

            while(rs1.next())
            {
                txtCity.setText(rs1.getString("City"));
                txtAddress.setText(rs1.getString("Address"));
                txtState.setText(rs1.getString("State"));
                txtZip.setText(rs1.getString("Zip"));
                //cusID = Integer.parseInt(String.valueOf("Customer_ID"));


                gotRecord = true;
            }


        }
        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }




    }

    public void newCustomer()
    {
        txtAddress.setEnabled(true);
        txtCity.setEnabled(true);
        txtZip.setEnabled(true);
        txtState.setEnabled(true);

        JOptionPane.showMessageDialog(frame,"Please Enter New Customer Information","New Customer",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public void addCustomer()
    {
        cusAddress = txtAddress.getText();
        cusCity = txtCity.getText();
        cusZip = txtZip.getText();
        cusState = txtState.getText();
        customerLast = txtCustomerLastName.getText();
        customerPhone = txtCustomerPhone.getText();

                try
        {
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stmt.executeUpdate("INSERT INTO customers (CustomerLast, Address, City, State, Zip, Phone) VALUES ('"
                    + customerLast + "', '" + cusAddress + "', '"  + cusCity + "', '" + cusState + "', '"
                    + cusZip + "', '"+ customerPhone + "')");

            stmt.executeQuery("SELECT Max(Customer_ID) From customers;");
            ResultSet rs1 = stmt.getResultSet();
            cusID = Integer.parseInt(String.valueOf("Max(Customer_ID)"));

        }
        catch(SQLException ex)
        {
            System.out.println(ex.getMessage());
        }

    }

    public void continueOrder()
    {
//        if (radToGo.setSelected())
//        {
//
//        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGroupOrder = new javax.swing.ButtonGroup();
        pnlBackgroundColor = new javax.swing.JPanel();
        lblPizzajpg = new javax.swing.JLabel();
        pnlSmBlueStripe = new javax.swing.JPanel();
        pnlGreenStripe = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblSubHeading = new javax.swing.JLabel();
        radInHouse = new javax.swing.JRadioButton();
        radDelivery = new javax.swing.JRadioButton();
        radToGo = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        txtCustomerLastName = new javax.swing.JTextField();
        lblCustLast = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCustomerPhone = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtCustomerPhone = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        pnlBlueStripe = new javax.swing.JPanel();
        lblSubHeading1 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblZip = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        btnFindCustomer = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();
        lblOrderInfo = new javax.swing.JMenuBar();
        mnuMainMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuMainMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackgroundColor.setBackground(new java.awt.Color(249, 238, 205));

        lblPizzajpg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgPizza/tomato_pizza.jpg"))); // NOI18N
        lblPizzajpg.setText("lblPizzaPic");
        lblPizzajpg.setAlignmentY(0.0F);
        lblPizzajpg.setFocusable(false);
        lblPizzajpg.setIconTextGap(0);
        lblPizzajpg.setInheritsPopupMenu(false);

        pnlSmBlueStripe.setBackground(new java.awt.Color(0, 0, 141));
        pnlSmBlueStripe.setAlignmentX(0.0F);
        pnlSmBlueStripe.setAlignmentY(0.0F);
        pnlSmBlueStripe.setFocusable(false);
        pnlSmBlueStripe.setPreferredSize(new java.awt.Dimension(590, 30));

        javax.swing.GroupLayout pnlSmBlueStripeLayout = new javax.swing.GroupLayout(pnlSmBlueStripe);
        pnlSmBlueStripe.setLayout(pnlSmBlueStripeLayout);
        pnlSmBlueStripeLayout.setHorizontalGroup(
            pnlSmBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        pnlSmBlueStripeLayout.setVerticalGroup(
            pnlSmBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        pnlGreenStripe.setBackground(new java.awt.Color(0, 153, 0));
        pnlGreenStripe.setAlignmentY(0.4F);
        pnlGreenStripe.setPreferredSize(new java.awt.Dimension(420, 30));
        pnlGreenStripe.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlGreenStripeLayout = new javax.swing.GroupLayout(pnlGreenStripe);
        pnlGreenStripe.setLayout(pnlGreenStripeLayout);
        pnlGreenStripeLayout.setHorizontalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
        );
        pnlGreenStripeLayout.setVerticalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        lblHeading.setFont(new java.awt.Font("Garamond", 1, 24));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("CJS Pizza ");

        lblSubHeading.setFont(new java.awt.Font("Garamond", 1, 18));
        lblSubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubHeading.setText("Order Information");

        radInHouse.setBackground(new java.awt.Color(249, 238, 205));
        radGroupOrder.add(radInHouse);
        radInHouse.setFont(new java.awt.Font("Garamond", 0, 18));
        radInHouse.setText("In House");
        radInHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radInHouseActionPerformed(evt);
            }
        });

        radDelivery.setBackground(new java.awt.Color(249, 238, 205));
        radGroupOrder.add(radDelivery);
        radDelivery.setFont(new java.awt.Font("Garamond", 0, 18));
        radDelivery.setText("Delivery");
        radDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDeliveryActionPerformed(evt);
            }
        });

        radToGo.setBackground(new java.awt.Color(249, 238, 205));
        radGroupOrder.add(radToGo);
        radToGo.setFont(new java.awt.Font("Garamond", 0, 18));
        radToGo.setText("To Go");
        radToGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radToGoActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Garamond", 0, 18));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnContinue.setFont(new java.awt.Font("Garamond", 0, 18));
        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        txtCustomerLastName.setFont(new java.awt.Font("Garamond", 0, 18));
        txtCustomerLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCustomerLastName.setAutoscrolls(false);
        txtCustomerLastName.setMaximumSize(new java.awt.Dimension(6, 21));
        txtCustomerLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerLastNameActionPerformed(evt);
            }
        });
        txtCustomerLastName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtCustomerLastNameCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lblCustLast.setFont(new java.awt.Font("Garamond", 0, 18));
        lblCustLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustLast.setText("Last Name");
        lblCustLast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAddress.setFont(new java.awt.Font("Garamond", 0, 18));
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("Address");
        lblAddress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCustomerPhone.setFont(new java.awt.Font("Garamond", 0, 18));
        lblCustomerPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerPhone.setText("Phone");
        lblCustomerPhone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCity.setFont(new java.awt.Font("Garamond", 0, 18));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("City");
        lblCity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtAddress.setFont(new java.awt.Font("Garamond", 0, 18));
        txtAddress.setAutoscrolls(false);

        txtCustomerPhone.setFont(new java.awt.Font("Garamond", 0, 18));
        txtCustomerPhone.setAutoscrolls(false);
        txtCustomerPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPhoneActionPerformed(evt);
            }
        });

        txtCity.setFont(new java.awt.Font("Garamond", 0, 18));
        txtCity.setAutoscrolls(false);
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        pnlBlueStripe.setBackground(new java.awt.Color(0, 0, 141));
        pnlBlueStripe.setAlignmentX(0.0F);
        pnlBlueStripe.setAlignmentY(0.0F);
        pnlBlueStripe.setFocusable(false);
        pnlBlueStripe.setPreferredSize(new java.awt.Dimension(590, 30));

        javax.swing.GroupLayout pnlBlueStripeLayout = new javax.swing.GroupLayout(pnlBlueStripe);
        pnlBlueStripe.setLayout(pnlBlueStripeLayout);
        pnlBlueStripeLayout.setHorizontalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1283, Short.MAX_VALUE)
        );
        pnlBlueStripeLayout.setVerticalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        lblSubHeading1.setFont(new java.awt.Font("Garamond", 1, 18));
        lblSubHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubHeading1.setText("Customer Information");

        txtZip.setFont(new java.awt.Font("Garamond", 0, 18));
        txtZip.setAutoscrolls(false);

        txtState.setFont(new java.awt.Font("Garamond", 0, 18));
        txtState.setAutoscrolls(false);

        lblZip.setFont(new java.awt.Font("Garamond", 0, 18));
        lblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZip.setText("Zip Code");
        lblZip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblState.setFont(new java.awt.Font("Garamond", 0, 18));
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblState.setText("State");
        lblState.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnFindCustomer.setFont(new java.awt.Font("Garamond", 0, 18));
        btnFindCustomer.setText("Get Customer Info");
        btnFindCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindCustomerActionPerformed(evt);
            }
        });

        btnNewCustomer.setFont(new java.awt.Font("Garamond", 0, 18));
        btnNewCustomer.setText("Add New Customer");
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundColorLayout = new javax.swing.GroupLayout(pnlBackgroundColor);
        pnlBackgroundColor.setLayout(pnlBackgroundColorLayout);
        pnlBackgroundColorLayout.setHorizontalGroup(
            pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                    .addComponent(pnlBlueStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(lblSubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(590, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundColorLayout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addComponent(radInHouse)
                .addGap(76, 76, 76)
                .addComponent(radDelivery)
                .addGap(82, 82, 82)
                .addComponent(radToGo)
                .addGap(482, 482, 482))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(618, 618, 618)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(pnlSmBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(585, 585, 585)
                .addComponent(lblSubHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundColorLayout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress)
                    .addComponent(btnFindCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(txtCustomerPhone)
                    .addComponent(lblCustomerPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtState)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtZip)
                    .addComponent(lblCustLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(444, 444, 444))
        );
        pnlBackgroundColorLayout.setVerticalGroup(
            pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addComponent(pnlBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubHeading)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radDelivery)
                    .addComponent(radInHouse)
                    .addComponent(radToGo))
                .addGap(18, 18, 18)
                .addComponent(pnlSmBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubHeading1)
                .addGap(27, 27, 27)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustLast)
                    .addComponent(lblCustomerPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindCustomer)
                    .addComponent(btnNewCustomer))
                .addGap(54, 54, 54)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(lblZip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnContinue))
                .addGap(40, 40, 40))
        );

        mnuMainMenuFile.setText("File");
        mnuMainMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainMenuFileActionPerformed(evt);
            }
        });
        mnuMainMenuFile.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuMainMenuFileMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuMainMenuFile.add(jMenuItem1);

        mnuMainMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuMainMenuExit.setText("Exit");
        mnuMainMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainMenuExitActionPerformed(evt);
            }
        });
        mnuMainMenuFile.add(mnuMainMenuExit);

        lblOrderInfo.add(mnuMainMenuFile);

        setJMenuBar(lblOrderInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMainMenuFileMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuMainMenuFileMenuKeyPressed

}//GEN-LAST:event_mnuMainMenuFileMenuKeyPressed

    private void radInHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radInHouseActionPerformed
        OrderType = "InHouse";
        OrderPricing myOrderPricing = new OrderPricing();
        myOrderPricing.setDeliveryOption(OrderType);
    }//GEN-LAST:event_radInHouseActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtCustomerLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerLastNameActionPerformed

    }//GEN-LAST:event_txtCustomerLastNameActionPerformed

    private void txtCustomerPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPhoneActionPerformed
 

    }//GEN-LAST:event_txtCustomerPhoneActionPerformed

    private void txtCustomerLastNameCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtCustomerLastNameCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerLastNameCaretPositionChanged

    private void mnuMainMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainMenuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMainMenuFileActionPerformed

    private void mnuMainMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainMenuExitActionPerformed
        int result = JOptionPane.showConfirmDialog(
    frame,
    "Are you sure you want to exit?",
    "CJS Software Solutions",
    JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        System.exit(0);
    }           
    }//GEN-LAST:event_mnuMainMenuExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        MainMenuUI mainMenu = new MainMenuUI();        
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnFindCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindCustomerActionPerformed
        findCustomer();
        if(gotRecord)
        {

        }
        else
        {
            newCustomer();
        }
    }//GEN-LAST:event_btnFindCustomerActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        addCustomer();
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        insertNewOrder();
        System.out.println(""+cusID+ "    "+OrderType+ "   "+orderNum);
        PizzaOrderUI myPizzaOrderUI = new PizzaOrderUI(cusID, OrderType, orderNum);
        myPizzaOrderUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinueActionPerformed

    private void radDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDeliveryActionPerformed
        OrderType = "Delivery";
        OrderPricing myOrderPricing = new OrderPricing();
        myOrderPricing.setDeliveryOption(OrderType);
    }//GEN-LAST:event_radDeliveryActionPerformed

    private void radToGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radToGoActionPerformed
        OrderType = "ToGo";
        OrderPricing myOrderPricing = new OrderPricing();
        myOrderPricing.setDeliveryOption(OrderType);
    }//GEN-LAST:event_radToGoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        radGroupOrder.clearSelection();
        txtAddress.setText(null);
        txtCity.setText(null);
        txtCustomerLastName.setText(null);
        txtCustomerPhone.setText(null);
        txtState.setText(null);
        txtZip.setText(null);
        
    }//GEN-LAST:event_btnClearActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderInfoUI().setVisible(true);
            }
        });
    }

    int orderNum;
    int cusID = 1;
    String cusAddress;
    String cusCity;
    String cusZip;
    String cusState;
    String OrderType;
    String customerPhone;
    String customerLast;
    boolean gotRecord = false;
    JFrame frame;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnFindCustomer;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCustLast;
    private javax.swing.JLabel lblCustomerPhone;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JMenuBar lblOrderInfo;
    private javax.swing.JLabel lblPizzajpg;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblSubHeading;
    private javax.swing.JLabel lblSubHeading1;
    private javax.swing.JLabel lblZip;
    private javax.swing.JMenuItem mnuMainMenuExit;
    private javax.swing.JMenu mnuMainMenuFile;
    private javax.swing.JPanel pnlBackgroundColor;
    private javax.swing.JPanel pnlBlueStripe;
    private javax.swing.JPanel pnlGreenStripe;
    private javax.swing.JPanel pnlSmBlueStripe;
    private javax.swing.JRadioButton radDelivery;
    private javax.swing.ButtonGroup radGroupOrder;
    private javax.swing.JRadioButton radInHouse;
    private javax.swing.JRadioButton radToGo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCustomerLastName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables

}
