/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderConfirmationUI.java
 *
 * Created on Oct 2, 2011, 2:41:30 PM
 */

package pkgPizza;

/**
 *
 * @author Steve
 */
public class OrderConfirmationUI extends javax.swing.JFrame {

    /** Creates new form OrderConfirmationUI */
    public OrderConfirmationUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundColor = new javax.swing.JPanel();
        lblPizzajpg = new javax.swing.JLabel();
        lblSmlBlueStripe = new javax.swing.JPanel();
        pnlGreenStripe = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblSubHeading = new javax.swing.JLabel();
        btnCancelOrder = new javax.swing.JButton();
        btnCompleteOrder = new javax.swing.JButton();
        lblComments = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblFinalTotal = new javax.swing.JLabel();
        pnlBlueStripe = new javax.swing.JPanel();
        lblTotOrderDescription = new javax.swing.JLabel();
        lblFinalTotalDisplay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPizzaDescription = new javax.swing.JTextArea();
        btnEditPizza = new javax.swing.JButton();
        lblSubTotalLabel = new javax.swing.JLabel();
        lblSubTotalDisplay = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        txtDiscount = new javax.swing.JTextField();
        btnAddPizza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackgroundColor.setBackground(new java.awt.Color(249, 238, 205));

        lblPizzajpg.setIcon(new javax.swing.ImageIcon("E:\\Project\\tomato_pizza.jpg")); // NOI18N
        lblPizzajpg.setText("lblPizzaPic");
        lblPizzajpg.setAlignmentY(0.0F);
        lblPizzajpg.setFocusable(false);
        lblPizzajpg.setIconTextGap(0);
        lblPizzajpg.setInheritsPopupMenu(false);

        lblSmlBlueStripe.setBackground(new java.awt.Color(0, 0, 141));
        lblSmlBlueStripe.setAlignmentX(0.0F);
        lblSmlBlueStripe.setAlignmentY(0.0F);
        lblSmlBlueStripe.setFocusable(false);
        lblSmlBlueStripe.setPreferredSize(new java.awt.Dimension(590, 30));

        javax.swing.GroupLayout lblSmlBlueStripeLayout = new javax.swing.GroupLayout(lblSmlBlueStripe);
        lblSmlBlueStripe.setLayout(lblSmlBlueStripeLayout);
        lblSmlBlueStripeLayout.setHorizontalGroup(
            lblSmlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        lblSmlBlueStripeLayout.setVerticalGroup(
            lblSmlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        pnlGreenStripe.setBackground(new java.awt.Color(0, 153, 0));
        pnlGreenStripe.setAlignmentY(0.4F);
        pnlGreenStripe.setPreferredSize(new java.awt.Dimension(420, 30));
        pnlGreenStripe.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnlGreenStripeLayout = new javax.swing.GroupLayout(pnlGreenStripe);
        pnlGreenStripe.setLayout(pnlGreenStripeLayout);
        pnlGreenStripeLayout.setHorizontalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        pnlGreenStripeLayout.setVerticalGroup(
            pnlGreenStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        lblHeading.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("CJS Pizza ");

        lblSubHeading.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblSubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubHeading.setText("Order Confirmation");

        btnCancelOrder.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelOrder.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnCompleteOrder.setBackground(new java.awt.Color(51, 51, 51));
        btnCompleteOrder.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        btnCompleteOrder.setText("Complete Order");

        lblComments.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblComments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComments.setText("Comments");
        lblComments.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDiscount.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscount.setText("Discount");
        lblDiscount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblFinalTotal.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        lblFinalTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFinalTotal.setText("Order Total:");
        lblFinalTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pnlBlueStripe.setBackground(new java.awt.Color(0, 0, 141));
        pnlBlueStripe.setAlignmentX(0.0F);
        pnlBlueStripe.setAlignmentY(0.0F);
        pnlBlueStripe.setFocusable(false);
        pnlBlueStripe.setPreferredSize(new java.awt.Dimension(590, 30));

        javax.swing.GroupLayout pnlBlueStripeLayout = new javax.swing.GroupLayout(pnlBlueStripe);
        pnlBlueStripe.setLayout(pnlBlueStripeLayout);
        pnlBlueStripeLayout.setHorizontalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        pnlBlueStripeLayout.setVerticalGroup(
            pnlBlueStripeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        lblTotOrderDescription.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblTotOrderDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotOrderDescription.setText("Total Order Description");

        lblFinalTotalDisplay.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        lblFinalTotalDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFinalTotalDisplay.setText("$");
        lblFinalTotalDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtPizzaDescription.setColumns(20);
        txtPizzaDescription.setRows(5);
        txtPizzaDescription.setText("(1) Large Thin Crust Custom (4 item)  $12,99\n\tPepperoni\n\tMushroom\n\tOnion\n\tBlack Olive\n2) Medium Stuffed Crust Meat Lover's (5 items)\n\tDouble Pepperoni\n\tGround Beef\n\tHam\n\tOnion\n\tXtra Cheese\n\t\n");
        jScrollPane1.setViewportView(txtPizzaDescription);

        btnEditPizza.setBackground(new java.awt.Color(51, 51, 51));
        btnEditPizza.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        btnEditPizza.setText("Edit Last Pizza");

        lblSubTotalLabel.setBackground(new java.awt.Color(51, 51, 51));
        lblSubTotalLabel.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblSubTotalLabel.setText("Order Sub-Total:");

        lblSubTotalDisplay.setBackground(new java.awt.Color(51, 51, 51));
        lblSubTotalDisplay.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblSubTotalDisplay.setText("$");

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane2.setViewportView(txtComments);

        txtDiscount.setText("$$$$$$");
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        btnAddPizza.setBackground(new java.awt.Color(51, 51, 51));
        btnAddPizza.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        btnAddPizza.setText("Add Pizza");

        javax.swing.GroupLayout pnlBackgroundColorLayout = new javax.swing.GroupLayout(pnlBackgroundColor);
        pnlBackgroundColor.setLayout(pnlBackgroundColorLayout);
        pnlBackgroundColorLayout.setHorizontalGroup(
            pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(pnlBlueStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundColorLayout.createSequentialGroup()
                .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundColorLayout.createSequentialGroup()
                .addComponent(lblSubHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundColorLayout.createSequentialGroup()
                .addComponent(lblTotOrderDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(lblSubTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSubTotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(165, 165, 165)
                        .addComponent(btnCompleteOrder)
                        .addGap(162, 162, 162))
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE))
                    .addComponent(lblComments, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(lblSmlBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                                .addComponent(lblDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(288, 288, 288))
                            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                                .addComponent(lblFinalTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(lblFinalTotalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262))))
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnEditPizza, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(165, 165, 165)
                        .addComponent(btnAddPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)))
                .addContainerGap())
        );
        pnlBackgroundColorLayout.setVerticalGroup(
            pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPizzajpg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundColorLayout.createSequentialGroup()
                        .addComponent(pnlBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(pnlGreenStripe, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotOrderDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotalLabel)
                    .addComponent(lblSubTotalDisplay))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPizza)
                    .addComponent(btnEditPizza))
                .addGap(48, 48, 48)
                .addComponent(lblSmlBlueStripe, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblComments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinalTotal)
                    .addComponent(lblFinalTotalDisplay))
                .addGap(18, 18, 18)
                .addGroup(pnlBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompleteOrder)
                    .addComponent(btnCancelOrder))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblSubTotalDisplay.getAccessibleContext().setAccessibleName("lblDisplayTotal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderConfirmationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPizza;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnCompleteOrder;
    private javax.swing.JButton btnEditPizza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblFinalTotal;
    private javax.swing.JLabel lblFinalTotalDisplay;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPizzajpg;
    private javax.swing.JPanel lblSmlBlueStripe;
    private javax.swing.JLabel lblSubHeading;
    private javax.swing.JLabel lblSubTotalDisplay;
    private javax.swing.JLabel lblSubTotalLabel;
    private javax.swing.JLabel lblTotOrderDescription;
    private javax.swing.JPanel pnlBackgroundColor;
    private javax.swing.JPanel pnlBlueStripe;
    private javax.swing.JPanel pnlGreenStripe;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextArea txtPizzaDescription;
    // End of variables declaration//GEN-END:variables

}
